### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by txtsd** [jesec/rtorrent#1]
Do you plan to support libtorrent 2.0 eventually?

**Comment by jesec** [comment]
rTorrent uses libtorrent-rakshasa instead of libtorrent-rasterbar. There is absolutely no plan to switch to libtorrent-rasterbar, which is inferior when it comes to scalability and stability. qBittorrent is a good choice if you wish to use the latest version of libtorrent-rasterbar.

**Comment by txtsd** [comment]
Oh. Well are there any plans for `libtorrent-rakshasa` to support hybrid and v2 torrents?

**Comment by txtsd** [comment]
Found an issue https://github.com/rakshasa/libtorrent/issues/213 but no official response yet.

What are your plans for this fork?

**Comment by jesec** [comment]
BitTorrent protocol is working perfectly fine for the last 20 years, and I believe that it will continue doing so for the time being.

No consensus layer (BitTorrent protocol) change is planned as this moment. Stability and continuity are the paramount focuses of this project at the moment. At this stage, this project is intended to be merely a distribution. There will NOT be any consensus layer change unless:
1. I understand the BitTorrent protocol deep enough to be confident and comfortable about a change in consensus layer.
1. AND there are compelling reasons for such a change.
1. AND reasonable methods have been established to evaluate the behaviors of a change (to both trackers and peers) in a swarm of BitTorrent clients.
1. AND rakshasa abdicates maintainership.

**Comment by formlessdao** [comment]
> which is inferior when it comes to scalability and stability.

And what are the technical arguments for your statement?

**Comment by jesec** [comment]
> > which is inferior when it comes to scalability and stability.
> 
> And what are the technical arguments for your statement?

Keep them running for several weeks, and you would be very fortunate if you don’t get any issues.

I have to restart my qBittorrent instance regularly, because after a certain time it becomes stuck, even with such a light load. Note that it does perform better at DHT and public torrents, and that’s why I deployed an instance. 

Unfortunately it can’t handle thousands of torrents with tens of TBs of associated data. I already have enough “checking all your torrents” heart attacks. 

That’s from the user’s perspective. From the technical point of view, while I didn’t dive deep into their code base, I can observe that libtorrent-rasterbar spawns many threads and it doesn’t seem to manage the resource usage well. rTorrent uses only a fixed number of threads, and an event based architecture.

**Comment by formlessdao** [comment]
Has rakshasa abandoned his project? He does not seem to ever want to update rtorrent and merge fixes you include in your fork.
