### ISSUE TITLE
request: PKGBUILD

### ISSUE THREAD

**Issue by afontenot** [jesec/rtorrent#6]
Hey, thanks for your work on improving rtorrent. I'm also enjoying your nodejs-flood AUR package, and it would be great to see a PKGBUILD for your rtorrent fork in the AUR as well.

You might run into an issue where a moderator doesn't think your changes to rtorrent are substantive enough to merit an AUR package for it and deletes it. I've run into this before. In this case, if you could have the CI upload an up-to-date PKGBUILD to the [releases](https://github.com/jesec/rtorrent/releases), that would make it easier for Arch users to keep up to date with this package.

If you feel like it, it might be nice to have a CHANGES document listing the most significant changes you've made to vanilla rtorrent. I've been appreciating the access to sequential download from Flood, but it would be nice to know what else is different without having to trawl through commits. (A list of changes would also help justify an AUR package at some point, I suspect.)

**Comment by jesec** [comment]
Since this is a feature request, I am moving it to discussions. 

This is a good idea.

However, note that `PKGBUILD` is NOT a package. It is a "recipe" that instructs a set of scripts and build tools to compile a package from sources.

Unlike Flood, it is drastically more complicated to handle dependencies and build tools for a C++ program like rTorrent/libTorrent. While the procedures are quite established, it would take significant efforts to get all those things sorted out.

Alternatively, it might be an option to publish a `-bin` package, which simply downloads prebuilt deliverables. This is not encouraged by AUR guidelines, though.

I will certainly take a look when I have time.
